### ISSUE TITLE
カスタムマーカーの作成方法について

### ISSUE THREAD

**Issue by RefletsDansLeau** [mapbox/mapbox-YOLP#7]
お世話になります。
プログラミング初心者です。mapboxで「子育てマップ」を作成したく勉強しております。
カスタムマーカーについてご教示いただきたいのですが、質問する場所はこちらで合っておりますでしょうか？
----質問内容-----
【チュートリアル①】Google spreadsheetsのデータをマッピング（https://labs.mapbox.com/education/impact-tools/sheet-mapper/）」
はできたのですが、①に以下チュートリアル②のコードを足しても、カスタムマーカーへの変更ができません。

【チュートリアル②】カスタムマーカーに変更（https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/）

チュートリアル②では、style部分に以下の記述をしてカスタムマーカーに変更しているのですが、チュートリアル①には「.marker」に該当する部分がないため、カスタムマーカーが反映されないのだと思います。
--------------
.marker {
            background-image: url('写真の名称.png');
            background-size: cover;
            width: 50px;
            height: 50px;
            border-radius: 50%;
            cursor: pointer;
        }
----------
以下のソースのどの部分を修正すればカスタムマーカーに変更できるのかご教示くださいますでしょうか？よろしくお願いいたします。

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>なかマップ</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no'>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet">
    <script src="https://npmcdn.com/csv2geojson@latest/csv2geojson.js"></script>
    <script src="https://npmcdn.com/@turf/turf/turf.min.js"></script>

    <style>
        body {
            margin: 0;
            padding: 0;
        }

        #map {
            position: absolute;
            top: 0;
            bottom: 0;
            width: 100%;
        }

        /* Popup styling */

        .mapboxgl-popup {
            padding-bottom: 5px;
        }

        .mapboxgl-popup-close-button {
            display: none;
        }

        .mapboxgl-popup-content {
            font: 400 15px/22px 'Source Sans Pro', 'Helvetica Neue', Sans-serif;
            padding: 0;
            width: 250px;
        }

        .mapboxgl-popup-content-wrapper {
            padding: 1%;
        }

        .mapboxgl-popup-content h3 {
            background: rgb(206, 103, 103);
            text-align: center;
            color: #fff;
            margin: 0;
            display: block;
            padding: 15px;
            font-weight: 700;
            margin-top: -5px;
        }

        .mapboxgl-popup-content h4 {
            margin: 0;
            display: block;
            padding: 10px 3px 10px 10px;
            font-weight: 400;
        }

        .mapboxgl-container {
            cursor: pointer;
        }

        .mapboxgl-popup-anchor-top>.mapboxgl-popup-content {
            margin-top: 3px;
        }

        .mapboxgl-popup-anchor-top>.mapboxgl-popup-tip {
            border-bottom-color: rgb(61, 59, 59);
        }

        /*これでアイコンがどんぐりになるはずのだができない。
        .marker {
            background-image: url('acorn.png');
            background-size: cover;
            width: 50px;
            height: 50px;
            border-radius: 50%;
            cursor: pointer;
        }
*/
        .mapboxgl-popup {
            max-width: 200px;
        }

        .mapboxgl-popup-content {
            text-align: center;
            font-family: 'Open Sans', sans-serif;
        }
    </style>
</head>

<body>

    <div id='map'></div>
    <script>

        var transformRequest = (url, resourceType) => {
            var isMapboxRequest =
                url.slice(8, 22) === "api.mapbox.com" ||
                url.slice(10, 26) === "tiles.mapbox.com";
            return {
                url: isMapboxRequest
                    ? url.replace("?", "?pluginName=sheetMapper&")
                    : url
            };
        };
        //YOUR TURN: add your Mapbox token 2021/02/24 done

        mapboxgl.accessToken = 'pk.＊＊＊＊＊＊＊＊＊＊＊';//Mapbox token 2021/2/24 done
        var map = new mapboxgl.Map({
            container: 'map',// container id
            style: 'mapbox://styles/satko/cklk7igwj013418phpt6a3lws',// YOUR TURN: choose a style: https://docs.mapbox.com/api/maps/#styles
            center: [139.7670516, 35.6811673],// starting position [lng, lat] google mapやfoliumとは緯度経度情報が逆！
            zoom: 10,// starting zoom
            transformRequest: transformRequest
        });

        $(document).ready(function () {
            $.ajax({
                type: "GET",
                //YOUR TURN: Replace with csv export link ⇒2021/02/19　done
                url: 'https://docs.google.com/spreadsheets/d/＊＊＊＊＊＊＊＊/gviz/tq?tqx=out:csv&sheet=Sheet1',
                dataType: "text",
                success: function (csvData) { makeGeoJSON(csvData); }
            });

            function makeGeoJSON(csvData) {
                csv2geojson.csv2geojson(csvData, {
                    latfield: 'Latitude',
                    lonfield: 'Longitude',
                    delimiter: ','
                }, function (err, data) {
                    map.on('load', function () {

                        //Add the the layer to the map
                        map.addLayer({
                            'id': 'csvData',
                            'type': 'circle',　//symbleに変更するのかな？←ダメだった。
                            'source': {
                                'type': 'geojson',
                                'data': data
                            },
                            'paint': {
                                'circle-radius': 5,
                                'circle-color': "purple"
                            }
                        });

                        // When a click event occurs on a feature in the csvData layer, open a popup at the
                        // location of the feature, with description HTML from its properties.
                        map.on('click', 'csvData', function (e) {
                            var coordinates = e.features[0].geometry.coordinates.slice();

                            //set popup text
                            //You can adjust the values of the popup to match the headers of your CSV.
                            // For example: e.features[0].properties.Name is retrieving information from the field Name in the original CSV.
                            var description = `<h3>` + e.features[0].properties.Name + `</h3>` + `<h4>` + `<b>` + `遊具 ` + `</b>` + e.features[0].properties.equipment + `</h4>` + `<h4>` + `<b>` + `植物 ` + `</b>` + e.features[0].properties.plant + `</h4>`;

                            // Ensure that if the map is zoomed out such that multiple
                            // copies of the feature are visible, the popup appears
                            // over the copy being pointed to.
                            while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
                                coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
                            }

                            //add Popup to map

                            new mapboxgl.Popup()
                                .setLngLat(coordinates)
                                .setHTML(description)
                                .addTo(map);
                        });

                        // Change the cursor to a pointer when the mouse is over the places layer.
                        map.on('mouseenter', 'csvData', function () {
                            map.getCanvas().style.cursor = 'pointer';
                        });

                        // Change it back to a pointer when it leaves.
                        map.on('mouseleave', 'places', function () {
                            map.getCanvas().style.cursor = '';
                        });

                        var bbox = turf.bbox(data);
                        map.fitBounds(bbox, { padding: 50 });

                    });

                });
            };
        });

    </script>

</body>

</html>

**Comment by tsuz** [comment]
@RefletsDansLeau 

チケット立てて頂きありがとうございます。

GL JSのコードに関してですと、jsfiddle.netにてコードを隔離する上で、トラブルシューティングを行う事をお勧めいたします。

私の方で、上記のコードを以下の`jsfiddle`(公開版ですのでmapboxのアクセストークンと地図に置き換えました)に導入しましたので、`$.ajax`の`makeGeoJSON()`のデータを静的データに置き換えた上で、再度試していただけますか。コードのどの部分が期待値通りでないかコメントして頂き、保存した上で新たなリンクを頂ければ助かります。宜しくお願いします。

https://jsfiddle.net/ygamjcb2/3/

**Comment by RefletsDansLeau** [comment]
早急にお返事くださり、ありがとうございます。
当方、プログラミング初心者でして、ご回答いただいた部分の「$.ajaxのmakeGeoJSON()のデータを静的データに置き換え」が具体的に何を意味するのかが分かりません。チュートリアル①の通り、GoogleスプレッドシートのURLを埋め込んでみたのですが、これで大丈夫でしょうか？

**Comment by tsuz** [comment]
@RefletsDansLeau 

返答ありがとうございます。jsfiddle内で保存すると新しいURLが発行されるので、そちらをご提供お願いします。

**Comment by RefletsDansLeau** [comment]
こちらになります。
https://jsfiddle.net/9bakxz5u/1/

**Comment by RefletsDansLeau** [comment]
お世話になります。カスタムマーカーの件ですが、下記①②に掲載されているコードを参考にしたこともあるのですが、こちらもうまくきませんでした。
-----参考サイト------
① https://stackoverflow.com/questions/62927734/how-to-add-markers-instead-of-circles-with-csv2geojson-data
②https://docs.mapbox.com/jp/mapbox-gl-js/example/add-image/
-----jsfiddle-----
https://jsfiddle.net/9bakxz5u/3/  (Javascriptの50～69行目)

お手数をおかけしますが、csv2geojson データにカスタムアイコンを追加する方法について、ご教示くださいますよう、重ねてお願い申し上げます。

**Comment by tsuz** [comment]
@RefletsDansLeau 

返答ありがとうございます。こちらのリンクのコードはエラーが出てて、コンパイルできない様です。https://jsfiddle.net/9bakxz5u/3/

![Screen Shot 2021-03-02 at 16 32 43](https://user-images.githubusercontent.com/6927131/109613730-eb5b8b00-7b74-11eb-8e79-b0016bcfe75c.png)


パッと見た感じ、以下を確認する事を推奨します。
1. 画像の参照先が存在するか確かめてください。

2. この以下の`data`変数とその下の`GeoJSON`を比較することもお勧めします。

```
csv2geojson.csv2geojson(csvData, {
                latfield: 'Latitude',
                lonfield: 'Longitude',
                delimiter: ','
            }, function (err, data) {
```

```
'source': {
                        'type': 'geojson',
                        'data': {
                            'type': 'FeatureCollection',
                            'features': [
                                {
                                    'type': 'Feature',
                                    'geometry': {
                                        'type': 'Point',
                                        'coordinates': [0, 0]
                                    }
                                }
                            ]
                        }
                    },
```


こちらのデモに対しJSFiddleの実装が存在しますので、そちらを元に作成するのもアリかと考えています。
https://docs.mapbox.com/jp/mapbox-gl-js/example/add-image/

宜しくお願いします。

**Comment by RefletsDansLeau** [comment]
ご返答くださりありがとうございます。
ご指摘いただいた点を確認してみます。

**Comment by RefletsDansLeau** [comment]
お世話になります。

マーカーの画像について以下①②を確認しました。

①JSFiddleではローカルパスの画像ファイルは読み込めなかったです。結果⇒https://jsfiddle.net/bto1khf0/1/
パスについては過去に他の方が質問しておりました。⇒https://github.com/mapbox/mapbox-gl-js/issues/8037
②JSFiddleでは読み込めませんでしたが、私のPCのXAMPPでは読み込めました。
![test](https://user-images.githubusercontent.com/52129157/109748568-70e64600-7c1c-11eb-8c14-8aa200ef44bb.png)

またgeojsonのデータについてはこれから検証してみます。

**Comment by RefletsDansLeau** [comment]
コンパイルできないファイルのエラーを気合いで修正してみました。(素人なので直っているか不明ですが…。)
https://jsfiddle.net/kgrd074c/3/　の47-78行部分に、

テンプレート「https://jsfiddle.net/api/post/library/pure/」の8-39までコピー＆ペーストしてみたのですが、
表示されません。

**Comment by RefletsDansLeau** [comment]
できました！ありがとうございました！！！
https://jsfiddle.net/yfud9cak/
![test2](https://user-images.githubusercontent.com/52129157/109756734-cbd36980-7c2b-11eb-9114-37e9cde79858.png)

**Comment by RefletsDansLeau** [comment]
自作アイコンの画像をwikimediaにアップし、無事、カスタムマーカーにすることができました。
ありがとうございました。
https://jsfiddle.net/yfud9cak/1/
![test3](https://user-images.githubusercontent.com/52129157/109760712-87979780-7c32-11eb-9ff9-1ca2daefeca8.png)

**Comment by tsuz** [comment]
@RefletsDansLeau 
良かったです！ 🎉 
解決できた様なので、クローズいたします。
